# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
architect:
  - yegor256
docker:
  image: yegor256/rultor-image:1.24.0
install: |
  sudo apt-get install --yes python3-pygments
  sudo pip3 install pygments
  pdd --file=/dev/null
merge:
  script: |
    latexmk -pdf
